# Generated by Django 4.0.5 on 2022-06-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_offer_remove_food_discount_additions_food_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='foods.offer'),
        ),
    ]
