# Generated by Django 4.0.5 on 2022-06-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='food',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='foods.food'),
            preserve_default=False,
        ),
    ]
