# Generated by Django 4.0.5 on 2022-06-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_remove_food_offer_offer_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additions',
            new_name='Addition',
        ),
    ]
