# Generated by Django 4.0.5 on 2022-06-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_rename_additions_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='points',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addition',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='foods.food'),
        ),
    ]
