# Generated by Django 4.0.5 on 2022-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_food_points_alter_addition_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
