# Generated by Django 4.0.5 on 2022-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_food_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='value',
            field=models.FloatField(),
        ),
    ]
