# Generated by Django 4.0.5 on 2022-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_alter_food_price_alter_offer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='price',
            field=models.FloatField(),
        ),
    ]
