# Generated by Django 4.0.5 on 2022-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_alter_addition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
