# Generated by Django 4.0.5 on 2022-06-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_category_hide_food_hide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='hide',
            new_name='visibilty',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='hide',
            new_name='visibilty',
        ),
    ]
