# Generated by Django 4.0.5 on 2022-06-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_rename_hide_category_visibilty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='visibilty',
            new_name='visiblity',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='visibilty',
            new_name='visiblity',
        ),
    ]
