# Generated by Django 4.0.5 on 2022-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_rename_visibilty_category_visiblity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subTitle', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='advertises/')),
            ],
        ),
    ]
