# Generated by Django 4.0.5 on 2022-06-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foods.food'),
            preserve_default=False,
        ),
    ]
