# Generated by Django 4.0.5 on 2022-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_advertise_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='subTitle',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='visiblity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='visiblity',
            field=models.BooleanField(default=True),
        ),
    ]
