# Generated by Django 4.0.5 on 2022-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
