# Generated by Django 4.0.5 on 2022-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_alter_advertise_subtitle_alter_advertise_title_and_more'),
        ('accounts', '0006_user_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='favorites',
            field=models.ManyToManyField(to='foods.food'),
        ),
    ]
