# Generated by Django 4.0.5 on 2022-06-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='shareCodeValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='usersSharedConunt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
