# Generated by Django 4.0.5 on 2022-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_userssharedconunt_clientuser_userssharedcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='rate',
            field=models.PositiveIntegerField(choices=[(None, 'none'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
