# Generated by Django 4.0.5 on 2022-07-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_clientuser_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='city',
        ),
    ]
