# Generated by Django 4.0.5 on 2022-06-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_clientuser_points'),
        ('foods', '0006_food_points_alter_addition_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'free'), ('p', 'paid')], max_length=1)),
                ('count', models.PositiveSmallIntegerField()),
                ('additions', models.ManyToManyField(to='foods.addition')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
