# Generated by Django 4.0.5 on 2022-06-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_clientuser_user'),
        ('orders', '0002_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Oredr',
        ),
    ]
