# Generated by Django 4.0.3 on 2022-06-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_clientuser_user'),
        ('orders', '0005_remove_orderitem_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oredr',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
            preserve_default=False,
        ),
    ]
