# Generated by Django 4.0.5 on 2022-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_oredr_order_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('r', 'rejected'), ('c', 'cooking'), ('q', 'in queue'), ('w', 'waiting'), ('d', 'delivering'), ('f', 'finshed')], max_length=1),
        ),
    ]
