# Generated by Django 4.0.5 on 2022-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='freeItems',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='freeItems',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
