# Generated by Django 4.0.5 on 2022-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_cartitem_type_remove_orderitem_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
