# Generated by Django 4.0.5 on 2022-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_recievetieme_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recieveTieme',
            new_name='recieveTime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='inStore',
        ),
        migrations.AlterField(
            model_name='order',
            name='payMethod',
            field=models.CharField(choices=[('ca', 'cash'), ('cc', 'card'), ('rs', 'recieve from store')], max_length=2),
        ),
    ]
