# Generated by Django 4.0.5 on 2022-06-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_location_lat_alter_location_lng'),
        ('orders', '0013_rename_recievetieme_order_recievetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'coupon')},
        ),
    ]
