# Generated by Django 4.0.5 on 2022-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
