# Generated by Django 4.0.5 on 2022-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_coupon_users_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
