# Generated by Django 4.0.5 on 2022-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_note_cartitem_note_orderitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('r', 'rejected'), ('c', 'cooking'), ('q', 'in queue'), ('w', 'waiting'), ('d', 'delivering'), ('f', 'finshed'), ('t', 'terminate')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
